version: '3.9'

services:
  postgres_db:
    image: postgres:16.1-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  snake_eyes_api:
    image: aguryanov/snake-eyes-api:0.0.1
    container_name: snake_eyes_api
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      API_PORT: ${API_PORT:-5000}
      DB_URL: postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres_db:5432/${DB_NAME:-snake_eyes}
    ports:
      - "$API_PORT:$API_PORT"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:$API_PORT/ping || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  test_runner:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      snake_eyes_api:
        condition: service_healthy
    env_file:
      - ./.env
    command: [ "pytest", "tests/", "-v" ]

volumes:
  postgres_data:
